### ISSUE TITLE
Bitcoin send, confirmed in Multibit, and balance reduced but not received by the receiver.

### ISSUE THREAD

**Issue by meworking** [jim618/multibit#667]
Bug report
  Operating System: Windows 7
  MultiBit Version: 0.5.18
  Steps to replicate the problem:

I tried to Reset Blockchain and Transaction, no change. I checked the receiver's address if he received it, no he hasn't. I checked in my address in bitcoin info, it shows not sent. But I don't have the BTC in my account. Please look into the matter. Thank You.

**Comment by gary-rowe** [comment]
Sounds like an upstream transaction issue. Can you verify that you have read this help article: https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html

**Comment by meworking** [comment]
There are lots of tiny inputs (under 5432 satoshis) in your wallet and the transaction fires the anti-spam rules.
The fee is too small and the peer chooses not to relay it.
The transaction is a double spend. Doubles spends aren't relayed through the network.
Some other reason - this is not a definitive list.

It was 90$ transaction, so not a small one.
The fee was the normal one, I didn't changed it.
The transaction was not doubled, I just did that once.

Some other reasons? I don't know about that.

**Comment by gary-rowe** [comment]
The 90$ is the output, it is the inputs that are most likely causing the problem.

It might be that your copy of the SPV blockchain has become corrupted. This is normally automatically corrected in later versions of MultiBit and Reset Tx usually fixes things. However a "hard reset" of the SPV block chain can sometimes help with clearing out older transactions that are causing problems. 

Please try the following process:

1. Shut down MultiBit
2. Go to your MultiBit user data directory (something like `C:\Users\YourUsername\AppData\Roaming\MultiBit`) and delete the file `multibit.spvchain`. This directory may be hidden.
3. Start up MultiBit again
4. Wait for the synch process to complete - it may take some time since this is a "hard reset" of the block chain data

**Comment by meworking** [comment]
It is now working, I didn't do anything, just waited. But now it is stuck in 30 confirmation. The link is here: https://blockchain.info/tx-index/8299ac652e66f62d5c2aedbdc9e6092dd1c84f540b282792bcdcfab7a8b85eb3?show_adv=true

**Comment by gary-rowe** [comment]
Looking at it now I see 37 confirmations: https://btc.blockr.io/tx/info/8299ac652e66f62d5c2aedbdc9e6092dd1c84f540b282792bcdcfab7a8b85eb3

**Comment by meworking** [comment]
I still see 30 confirmations only, any problem in blockchain? https://blockchain.info/tx-index/8299ac652e66f62d5c2aedbdc9e6092dd1c84f540b282792bcdcfab7a8b85eb3

**Comment by gary-rowe** [comment]
Reddit seems to think there's a problem with BCI: http://www.reddit.com/r/Bitcoin/comments/2xgbv1/the_blockchaininfo_block_parser_is_stuck_last/

There is definitely a disparity.
